# Generated by Django 2.2 on 2022-01-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220129_2044'),
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
